# Generated by Django 3.2.4 on 2021-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='tovar',
            new_name='familya',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='curs',
            new_name='number',
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
