# Generated by Django 3.2.4 on 2021-06-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20210616_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
